### ISSUE TITLE
Don't understand day-50 portion, is there any resources for me to study?

### ISSUE THREAD

**Issue by qiansen1386** [coells/100days#10]
[day-50-conways-game-of-life#algorithm](https://render.githubusercontent.com/view/ipynb?commit=986a81130a1378b12e6d81f3fac187a025e1be2c&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f636f656c6c732f313030646179732f393836613831313330613133373862313265366438316633666163313837613032356531626532632f64617925323035302532302d25323067616d652532306f662532306c6966652e6970796e62&nwo=coells%2F100days&path=day+50+-+game+of+life.ipynb&repository_id=86095123&repository_type=Repository#algorithm)

Thank you so much for sharing this!
It's like a mind-blowing magic, but why. I guess we cannot understand what are you doing if we don't have the background knowledge of FFT
Can we use scipy.signal package to do the job?

**Comment by coells** [comment]
Hey! 

In Conway's game we take each cell one by one and count up the number of activated neighbours to apply given rule. E.g. if cell is active and has less then 2 active neighbours, it is deactivated (it dies). That's an algorithm you would easily write using 3 embedded for-loops.

What you can do, instead, is to define a 2D kernel function in form
```
[1  1 1]
[1 10 1]
[1  1 1]
```
The game board is another 2D function that looks like
```
```

I think you can understand the code without FT. What I do?

**Comment by qiansen1386** [comment]
Thank you so much for the explanation!!
