### ISSUE TITLE
Complexity for each algorithm

### ISSUE THREAD

**Issue by cristaloleg** [coells/100days#3]
What do you think about adding complexity to all algorithms?

Something like:
![image](https://user-images.githubusercontent.com/366002/27393430-97a84b5e-56a9-11e7-862d-c57480f5f6fd.png)

**Comment by coells** [comment]
The series at https://medium.com/100-days-of-algorithms sometimes contains discussion about complexity. I do not plan any further changes or improvements in the notebooks, here.
