### ISSUE TITLE
What about using tech.io

### ISSUE THREAD

**Issue by fraisse** [coells/100days#5]
Hi Tomáš,

This is a nice content you have crafted. Thanks for the work.
However I do not really want to download and install a soft just to have a test.
Have you ever heard about the tech.io platform? Seems to be perfectly adapted for this kind of content. Can you consider to try it to "translate" your content on it?

**Comment by coells** [comment]
Thanks a lot, Sylvain.

The challenge is over and at this time I do not plan any further development, as I do not have any free time to spend at this moment. The notebooks are also available at [Microsoft Azure](https://notebooks.azure.com/coells/libraries) as out-of-the-box solution. All you need is to clone the library and you can run all the algorithms.

Hope this helps!
