### ISSUE TITLE
Trying to understand the union find

### ISSUE THREAD

**Issue by kounkou** [coells/100days#9]
Hey @coells,

Could you provide some details about the union find code please?
For instance if I give the following intervals as input :

```bash
[[1,2], [2,3], [4,5]]
```
why do I get as output :

```bash
('item', 0, '-> component', 0)
('item', 1, '-> component', 3)
('item', 2, '-> component', 3)
('item', 3, '-> component', 3)
('item', 4, '-> component', 5)
('item', 5, '-> component', 5)
('item', 6, '-> component', 6)
('item', 7, '-> component', 7)
('item', 8, '-> component', 8)
('item', 9, '-> component', 9)
```

Should I just ignore items 0, 6 -> 9 ? and notice that items 1, 2, 3 are as expected in the same group, and 4, 5 in another group?

regards

**Comment by coells** [comment]
Union-find is data structure that handles unification of **equivalence classes**, not intervals.

In your case `[[1,2], [2,3], [4,5]]` translates to `1=2, 2=3, 4=5` which means that you have two classes of equivalence `{1, 2, 3}, {4, 5}` and hence the algorithm outputs their components accordingly.
